### ISSUE TITLE
Dreambooth with Oneflow

### ISSUE THREAD

**Issue by abi98213** [Oneflow-Inc/onediff#132]
Hey thanks for your awesome repo,
Is it possible to run dreambooth with oneflow ? It would make is very fast for training dreambooth.
Thanks

**Comment by chavinlo** [comment]
@CPFLAME Aproximately how much is the speedup vs. HuggingFace's trainer?

**Comment by CPFLAME** [comment]
> @CPFLAME Aproximately how much is the speedup vs. HuggingFace's trainer?

with same configue  as huggingface:  1gpu + fp16 + checkpointing + batch_size=1 
libai vs huggingface :   5.59 samples/s  vs 2.10 iter/s

here is huggingface dreambooth config:
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false
```

running dreambooth command in hugging face:
```shell
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="./demo_dog/"
export OUTPUT_DIR="./output/"


accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="a photo of sks dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=20
```
